language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
# See tox.ini for env list
env:
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=py35-django111
install:
  - pip install tox coverage coveralls
script:
  - tox
notifications:
    irc:
        - "irc.freenode.org#django-wiki"
sudo: false
after_success:
  - coverage combine
  - codecov

