# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 16:50
from __future__ import unicode_literals

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nyt', '0006_auto_20141229_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default for new subscriptions'),
        ),
    ]
