# Generated by Django 4.0.2 on 2022-02-12 22:40
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nyt', '0008_auto_20161023_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_nyt.subscription', verbose_name='subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_nyt.notificationtype', verbose_name='notification type'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_nyt.settings', verbose_name='settings'),
        ),
    ]
