# Generated by Django 4.2.1 on 2024-01-06 22:12
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("django_nyt", "0009_alter_notification_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_sent",
            field=models.DateTimeField(blank=True, null=True, verbose_name="last sent"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_emailed",
            field=models.BooleanField(default=False, verbose_name="mail sent"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_viewed",
            field=models.BooleanField(
                default=False, verbose_name="notification viewed"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="url",
            field=models.CharField(
                blank=True,
                max_length=2000,
                null=True,
                verbose_name="link for notification",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="interval",
            field=models.SmallIntegerField(
                choices=[(0, "instantly"), (1380, "daily"), (9660, "weekly")],
                default=0,
                help_text="interval in minutes (0=instant, 60=notify once per hour)",
                verbose_name="interval",
            ),
        ),
    ]
